### ISSUE TITLE
analytic submodule not included in pip package

### ISSUE THREAD

**Issue by tjueterb** [pyfar/pyrato#26]
Hi Everyone,

in the Demo Notebook `energy_decay_curves_and_reverberation_time` the line `from pyrato import analytic` throws an import error:
```python
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[3], line 1
----> 1 from pyrato import analytic

ImportError: cannot import name 'analytic' from 'pyrato' (/srv/conda/envs/notebook/lib/python3.10/site-packages/pyrato/__init__.py)
```
The `analytic` submodule does not seem to be included in the package distributed by pip. This happens locally on my machine, but also in the [binder notebook](https://notebooks.gesis.org/binder/jupyter/user/pyfar-pyrato-h7sz3kzk/notebooks/examples/energy_decay_curves_and_reverberation_time.ipynb).

Best,
Tobi

**Comment by mberz** [comment]
Thanks for catching this. The analytic module has been removed from the top level init file.
Can you try importing it via

```python
import pyrato.analtic as analytic
```
or 
```python
import pyrato.analtic
```

**Comment by tjueterb** [comment]
The import works when I clone the repo and run the commands from the home directory of the repo, but if I use the installation I got from `pip install pyrato`, both
```python
import pyrato.analytic as analytic
```
and
```python
import pyrato.analytic
```
give me the error
```bash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pyrato.analytic'

```
The `pyrato` installation in my environment doesn't contain the `analytics` folder:
![image](https://github.com/user-attachments/assets/c9533f32-6525-46c0-a6b8-4dc322e9a6ee)

**Comment by mberz** [comment]
Thanks for looking into the issue, Tobi. 
I'll prepare a fix for this issue soon.
